### ISSUE TITLE
Add support for normal ANSI bottom row

### ISSUE THREAD

**Issue by JarTheHead** [dededecline/SST80#1]
Adding support for ANSI bottom row would be helpful for users that may want that layout.

**Comment by dededecline** [comment]
SST stands for "split space tsangan" - the ethos behind these PCBs is to prioritize Tsangan bottom rows (1.5/1/1.5/7/1.5/1/1.5) and split space layouts that can conveniently work with Tsangan bottom rows without inducing excessive swiss cheese on the PCB. Adding ANSI support would go pretty directly against the spirit of SST so this will not be accommodated, but forks are always welcome.
